### ISSUE TITLE
Complete signup endpoint

### ISSUE THREAD

**Issue by chhavikant-01** [chhavikant-01/cryptic-cave#3]
### Branch: Dev
- The **yearOfgraduation** and **program** are required (currently commented out) according to the `user.model.js` file. 
- But it is not handled by the signup function in `auth.controller.js` when the `/api/auth/signup` endpoint is called.

**Comment by KINGSMAN6150** [comment]
HI chavikant just formed a signup function in controller so check it out and i have maded necessary comments so please check and i think the issue has been solved
@chhavikant-01
